### PR TITLE
2nd day - for react basics

### PR DESCRIPTION
**Pull request by Tripjack-SumitChandra**
I have used static function getDerivedStateFromProps().

### CODE REVIEW

**Review by varunTripjack — APPROVED** [review]
reviewed

**Review by AshishTripjack — APPROVED** [review]
Good Job, keep it

**Review by tripwithrudra — APPROVED** [review]
### No changes needed.

**Review by Isha-tripjack — COMMENTED** [review]
chnages needed

**Review by Isha-tripjack — APPROVED** [review]
no changes needed

**Pull request merged**
